class_name RideFidelityReferences
extends RefCounted

## Reviewed executable subset of the repository telemetry corpus. This deliberately records only
## facts that can be compared with generated element families or that explain an evidence gap; the
## source documents remain authoritative and their 1 Hz tables are not copied here.
const CATALOG := {
	"schema_version": 1,
	"catalog_version": "2026-08-09.1",
	"sources": {
		"do_dodonpa_rfdb": {
			"document": "docs/TELEMETRY.md",
			"section": "1.6(d) Do-Dodonpa — highest measured launch acceleration",
			"confidence": "medium",
			"caveats": [
				"Consumer IMU recordings rather than instrumented track data.",
				"The recorded value is a peak; no common retained hold is published.",
			],
		},
		"falcon_cgi": {
			"document": "docs/RESEARCH.md",
			"section": "4. CGI-derived geometry",
			"confidence": "medium",
			"caveats": [
				"Design-intent rendering, not survey data.",
				"Real POV overrides the CGI wherever they disagree.",
			],
		},
		"falcon_pov": {
			"document": "docs/RESEARCH.md",
			"section": "2. Falcon's Flight — POV re-analysis",
			"confidence": "high",
			"caveats": [
				"Absolute speed is geometry-derived; motion analysis supports timing and trends only.",
			],
		},
		"falcon_review_overlay": {
			"document": "docs/TELEMETRY.md",
			"section": "SOURCE 2 — CoasterTalk Falcon's Flight Review",
			"confidence": "high",
			"caveats": [
				"Values are read from an on-video overlay rather than a downloadable trace.",
				"Two runs provide front/back corroboration but not every element is visible.",
			],
		},
		"falcon_rfdb_4804": {
			"document": "docs/TELEMETRY.md",
			"section": "1.1 Falcon's Flight — PRIMARY REFERENCE",
			"confidence": "low",
			"caveats": [
				"RideForcesDB flags this sole wrist-mounted recording as unreliable.",
				"Use smoothed sustained values only; the 99–100 s shock burst is excluded.",
			],
		},
		"i305_overlay": {
			"document": "docs/TELEMETRY-I305.md",
			"section": "1–3. Element timeline and family character",
			"confidence": "medium",
			"caveats": [
				"Phone normal-g overlay is accurate to about ±0.15 g and ±0.15 s.",
				"Element labels are good-confidence POV synchronization, not certified layout data.",
			],
		},
		"research_envelope": {
			"document": "docs/RESEARCH.md",
			"section": "5. Envelope (~2041) — grounding and final numbers",
			"confidence": "high",
			"caveats": [
				"These are user-adopted near-future design limits, not measurements of a real coaster.",
				"Duration-structured curves remain mandatory; brief limits are not flat targets.",
			],
		},
		"tormenta_rfdb": {
			"document": "docs/TELEMETRY.md",
			"section": "1.2 Tormenta Rampaging Run",
			"confidence": "medium",
			"caveats": [
				"Two consumer-IMU recordings agree on durations but differ in peak amplitude by seat.",
				"Neither recording carries an angle channel; element identity is order-matched.",
			],
		},
	},
	"targets": [
		{
			"id": "flow.i305_transition_swing",
			"source_ids": ["i305_overlay"],
			"confidence": "medium",
			"caveats": ["Compares the largest generated seam swing with I305's typical full-scale transitions."],
			"selector": {"scope": "route"},
			"dimension": "flow",
			"metric": "transition_force_swing",
			"recording_row": "unknown",
			"raw_range": [3.5, 4.7],
			"transform": {"kind": "identity", "factor": 1.0},
			"hold_seconds": null,
			"target_range": [3.5, 4.7],
			"seed_aggregation": "maximum",
			"issues": [10, 15],
		},
		{
			"id": "geometry.camelback_height",
			"source_ids": ["falcon_cgi", "falcon_pov"],
			"confidence": "medium",
			"caveats": ["The structure is 163–165 m; operating trim is irrelevant to geometry."],
			"selector": {"scope": "beat", "phase": "camelback", "kind": "hill"},
			"dimension": "geometry",
			"metric": "height",
			"recording_row": "not-applicable",
			"raw_range": [163.0, 165.0],
			"transform": {"kind": "identity", "factor": 1.0},
			"hold_seconds": null,
			"target_range": [163.0, 165.0],
			"seed_aggregation": "maximum",
			"issues": [14],
		},
		{
			"id": "geometry.camelback_max_pitch",
			"source_ids": ["falcon_cgi"],
			"confidence": "medium",
			"caveats": ["CGI indicates about 68–69° ascent and 60° descent."],
			"selector": {"scope": "beat", "phase": "camelback", "kind": "hill"},
			"dimension": "geometry",
			"metric": "max_pitch",
			"recording_row": "not-applicable",
			"raw_range": [60.0, 69.0],
			"transform": {"kind": "identity", "factor": 1.0},
			"hold_seconds": null,
			"target_range": [60.0, 69.0],
			"seed_aggregation": "maximum",
			"issues": [4, 14],
		},
		{
			"id": "geometry.camelback_width",
			"source_ids": ["falcon_cgi"],
			"confidence": "medium",
			"caveats": ["Derived from the CGI width:height ratio 1.81:1 and 163–165 m structure height."],
			"selector": {"scope": "beat", "phase": "camelback", "kind": "hill"},
			"dimension": "geometry",
			"metric": "width",
			"recording_row": "not-applicable",
			"raw_range": [295.0, 299.0],
			"transform": {"kind": "identity", "factor": 1.0},
			"hold_seconds": null,
			"target_range": [295.0, 299.0],
			"seed_aggregation": "maximum",
			"issues": [4, 14],
		},
		{
			"id": "geometry.cliff_dive_pitch",
			"source_ids": ["falcon_pov", "tormenta_rfdb"],
			"confidence": "high",
			"caveats": ["Falcon is 90°; Tormenta's comparable held drop is 95° beyond vertical."],
			"selector": {"scope": "beat", "phase": "dive + LSM3", "kinds": ["fall", "pushover"]},
			"dimension": "geometry",
			"metric": "min_pitch",
			"recording_row": "not-applicable",
			"raw_range": [-95.0, -90.0],
			"transform": {"kind": "identity", "factor": 1.0},
			"hold_seconds": null,
			"target_range": [-95.0, -90.0],
			"seed_aggregation": "minimum",
			"issues": [5, 14],
		},
		{
			"id": "geometry.clifftop_element_height",
			"source_ids": ["falcon_cgi"],
			"confidence": "low",
			"caveats": ["Converted the stated one-eighth to one-twelfth camelback scale into metres."],
			"selector": {"scope": "beat", "phase": "clifftop", "kinds": ["hill", "rim_turn", "turn"]},
			"dimension": "geometry",
			"metric": "height",
			"recording_row": "not-applicable",
			"raw_range": [13.6, 20.6],
			"transform": {"kind": "identity", "factor": 1.0},
			"hold_seconds": null,
			"target_range": [13.6, 20.6],
			"seed_aggregation": "maximum",
			"issues": [1, 14],
		},
		{
			"id": "loads.do_dodonpa_entry_peak",
			"source_ids": ["do_dodonpa_rfdb", "research_envelope"],
			"confidence": "medium",
			"caveats": ["Peak comparison only; the source does not establish a common sustained hold."],
			"selector": {"scope": "beat", "name": "Entry launch", "generated_row": "rear"},
			"dimension": "loads",
			"metric": "longitudinal_peak_positive",
			"recording_row": "mixed recordings",
			"raw_range": [3.17, 3.77],
			"transform": {"kind": "scale", "factor": 1.1},
			"hold_seconds": null,
			"target_range": [3.487, 4.147],
			"seed_aggregation": "maximum",
			"issues": [3, 9],
		},
		{
			"id": "loads.falcon_camelback_airtime_2_78s",
			"source_ids": ["falcon_rfdb_4804"],
			"confidence": "low",
			"caveats": ["Sustained camelback value is retained, but the source recording is globally unreliable."],
			"selector": {"scope": "beat", "phase": "camelback", "kind": "hill", "generated_row": "rear"},
			"dimension": "loads",
			"metric": "normal_held_negative",
			"recording_row": "row 7 left",
			"raw_range": [-0.61, -0.61],
			"transform": {"kind": "scale", "factor": 1.5},
			"hold_seconds": 2.78,
			"target_range": [-0.915, -0.915],
			"seed_aggregation": "minimum",
			"issues": [3, 13, 14],
		},
		{
			"id": "loads.falcon_first_drop_ejector_0_8s",
			"source_ids": ["falcon_rfdb_4804"],
			"confidence": "low",
			"caveats": ["The sustained 0.8 s segment is retained; short raw shocks are excluded."],
			"selector": {"scope": "beat", "kind": "twisted_drop", "generated_row": "rear"},
			"dimension": "loads",
			"metric": "normal_held_negative",
			"recording_row": "row 7 left",
			"raw_range": [-0.99, -0.5],
			"transform": {"kind": "scale", "factor": 1.5},
			"hold_seconds": 0.8,
			"target_range": [-1.485, -0.75],
			"seed_aggregation": "minimum",
			"issues": [3, 13],
		},
		{
			"id": "loads.i305_ejector_1s",
			"source_ids": ["i305_overlay", "research_envelope"],
			"confidence": "medium",
			"caveats": ["Uses the four I305 hills that sustain below −0.35 g for more than one second."],
			"selector": {"scope": "beat", "kinds": ["hill", "wave_turn"], "generated_row": "rear"},
			"dimension": "loads",
			"metric": "normal_held_negative",
			"recording_row": "unknown",
			"raw_range": [-1.15, -0.35],
			"transform": {"kind": "scale", "factor": 1.5},
			"hold_seconds": 1.0,
			"target_range": [-1.725, -0.525],
			"seed_aggregation": "minimum",
			"issues": [3, 13],
		},
		{
			"id": "loads.i305_turn_1_4s",
			"source_ids": ["i305_overlay", "research_envelope"],
			"confidence": "medium",
			"caveats": ["Uses I305's sustained banked-turn family rather than its brief local peaks."],
			"selector": {"scope": "beat", "kinds": ["turn", "overbank"], "generated_row": "rear"},
			"dimension": "loads",
			"metric": "normal_held_positive",
			"recording_row": "unknown",
			"raw_range": [3.5, 4.8],
			"transform": {"kind": "scale", "factor": 1.3333333333},
			"hold_seconds": 1.4,
			"target_range": [4.6666666666, 6.4],
			"seed_aggregation": "maximum",
			"issues": [3, 11],
		},
		{
			"id": "loads.tormenta_pullout_2_8s",
			"source_ids": ["tormenta_rfdb", "research_envelope"],
			"confidence": "medium",
			"caveats": ["Cross-recording drop-pullout sustain agrees; peak range carries seat variance."],
			"selector": {"scope": "beat", "kind": "pullout", "generated_row": "rear"},
			"dimension": "loads",
			"metric": "normal_held_positive",
			"recording_row": "front/back unknown",
			"raw_range": [3.0, 5.02],
			"transform": {"kind": "scale", "factor": 1.3333333333},
			"hold_seconds": 2.8,
			"target_range": [4.0, 6.6933333332],
			"seed_aggregation": "maximum",
			"issues": [3, 14],
		},
		{
			"id": "pacing.falcon_clifftop_crawl",
			"source_ids": ["falcon_pov"],
			"confidence": "high",
			"caveats": ["The 2.9–4.0 s crawl is before the edge traverse, not a hold at the dive lip."],
			"selector": {"scope": "beat", "phase": "clifftop"},
			"dimension": "pacing",
			"metric": "flat_seconds",
			"recording_row": "front and backwards POV",
			"raw_range": [2.9, 4.0],
			"transform": {"kind": "identity", "factor": 1.0},
			"hold_seconds": null,
			"target_range": [2.9, 4.0],
			"seed_aggregation": "maximum",
			"issues": [1, 11, 12],
		},
		{
			"id": "pacing.falcon_first_drop_duration",
			"source_ids": ["falcon_pov"],
			"confidence": "high",
			"caveats": ["POV timing is approximate but the element boundaries are visually clear."],
			"selector": {"scope": "beat", "kind": "twisted_drop"},
			"dimension": "pacing",
			"metric": "duration",
			"recording_row": "front POV",
			"raw_range": [4.3, 4.7],
			"transform": {"kind": "identity", "factor": 1.0},
			"hold_seconds": null,
			"target_range": [4.3, 4.7],
			"seed_aggregation": "maximum",
			"issues": [11, 14],
		},
		{
			"id": "pacing.falcon_low_section_duration",
			"source_ids": ["falcon_pov"],
			"confidence": "high",
			"caveats": ["Applies to the generated act-one low section as a phase total."],
			"selector": {"scope": "phase", "phase": "act one"},
			"dimension": "pacing",
			"metric": "duration",
			"recording_row": "front POV",
			"raw_range": [26.0, 28.0],
			"transform": {"kind": "identity", "factor": 1.0},
			"hold_seconds": null,
			"target_range": [26.0, 28.0],
			"seed_aggregation": "sum",
			"issues": [1, 11],
		},
		{
			"id": "terrain.act_one_hugging_share",
			"source_ids": ["falcon_pov", "falcon_cgi"],
			"confidence": "low",
			"caveats": ["The source is qualitative; the 80–100% band is a review aid, not gate-quality evidence."],
			"selector": {"scope": "phase", "phase": "act one"},
			"dimension": "terrain",
			"metric": "terrain_hugging_share",
			"recording_row": "not-applicable",
			"raw_range": [0.8, 1.0],
			"transform": {"kind": "identity", "factor": 1.0},
			"hold_seconds": null,
			"target_range": [0.8, 1.0],
			"seed_aggregation": "median",
			"issues": [6, 12],
		},
	],
	"review_prompts": [
		{
			"id": "review.element_shaping",
			"category": "element shaping",
			"prompt": "Do crests, pullouts, inversions, and roll timing read as deliberate family-specific shapes?",
			"source_ids": ["falcon_cgi", "falcon_pov"],
			"issues": [4, 5, 7, 14, 16],
		},
		{
			"id": "review.ride_feel",
			"category": "ride feel",
			"prompt": "Does each act alternate force, release, suspense, and recovery without dead connective track?",
			"source_ids": ["i305_overlay", "falcon_pov"],
			"issues": [1, 10, 11, 13, 15, 16],
		},
		{
			"id": "review.speed_perception",
			"category": "speed perception",
			"prompt": "Do near-ground reference points, tunnel walls, and element spacing make the modeled speed legible?",
			"source_ids": ["falcon_pov", "falcon_cgi"],
			"issues": [6, 8, 11, 12, 16],
		},
		{
			"id": "review.support_overlap",
			"category": "support overlap",
			"prompt": "Do seed-42 side/top views show track or supports visually colliding around inversions and crossings?",
			"source_ids": ["falcon_cgi"],
			"issues": [7, 16],
		},
	],
	"evidence_gaps": [
		{
			"id": "gap.absolute_agl",
			"description": "The corpus establishes terrain-hugging character but no surveyed per-element AGL band.",
			"source_ids": ["falcon_pov", "falcon_cgi"],
			"issues": [6, 12],
		},
		{
			"id": "gap.connective_micro_elements",
			"description": "The corpus identifies missing connective beats qualitatively but does not provide a reusable numeric family target.",
			"source_ids": ["falcon_pov"],
			"issues": [1, 4, 16],
		},
		{
			"id": "gap.coasting_drag",
			"description": "POV establishes monotonic speed loss but not an absolute drag coefficient or speed-loss band.",
			"source_ids": ["falcon_pov"],
			"issues": [2, 8, 11],
		},
		{
			"id": "gap.support_geometry",
			"description": "No reusable numeric support-clearance target exists in the telemetry corpus.",
			"source_ids": ["falcon_cgi"],
			"issues": [7],
		},
	],
}
