class_name RideFidelityReferences
extends RefCounted

const FALLBACK_CITATIONS := {
	"4804": [{
		"document": "docs/TELEMETRY.md", "section_id": "1.1-falcons-flight-primary-reference",
		"line_anchor": "lines 52-176", "columns_used": ["t (s)", "Element", "Vert (g)", "Lat (g)", "Long (g)", "Angle", "Notes"],
		"source_windows_used": [[16.3, 17.38], [44.5, 48.5], [78.0, 90.3], [90.5, 92.7], [99.02, 102.32], [102.9, 109.66], [151.6, 156.0]],
	}],
	"6369": [
		{
			"document": "docs/TELEMETRY.md", "section_id": "1.2-tormenta-per-element-cross-recording",
			"line_anchor": "lines 347-423", "columns_used": ["Element (RCDB order)", "t (6369)", "Duration", "Peak vert (6383 / 6369)", "Hold", "Notes"],
			"source_windows_used": [[7.38, 9.24], [10.2, 13.8], [18.04, 21.58], [23.5, 28.52], [32.0, 44.0], [45.92, 47.34], [47.7, 50.26], [52.7, 54.58], [56.34, 58.02], [61.46, 62.24]],
		},
		{
			"document": "docs/TELEMETRY.md", "section_id": "appendix-c-tormenta-rec-6369-back-right",
			"line_anchor": "lines 513-602", "columns_used": ["t", "Vmean", "Vmin", "Vmax", "Lmin", "Lmax", "Gmin", "Gmax"],
			"source_windows_used": [[0.0, 84.0]],
		},
	],
	"6383": [
		{
			"document": "docs/TELEMETRY.md", "section_id": "1.2-tormenta-per-element-cross-recording",
			"line_anchor": "lines 347-423", "columns_used": ["Element (RCDB order)", "t (6383)", "Duration", "Peak vert (6383 / 6369)", "Hold", "Notes"],
			"source_windows_used": [[7.28, 9.06], [9.84, 13.56], [17.6, 21.16], [22.94, 27.58], [31.8, 42.0], [44.68, 45.62], [46.08, 48.9], [50.94, 53.16], [54.5, 56.24], [59.58, 60.4]],
		},
		{
			"document": "docs/TELEMETRY.md", "section_id": "appendix-b-tormenta-rec-6383-row-2",
			"line_anchor": "lines 424-511", "columns_used": ["t", "Vmean", "Vmin", "Vmax", "Lmin", "Lmax", "Gmin", "Gmax"],
			"source_windows_used": [[0.0, 82.0]],
		},
	],
}

## This is provenance metadata, not a telemetry copy. Empty observations and targets are deliberate:
## the committed material has no source-to-generated alignment qualified for an executable band.
const CATALOG := {
	"schema_version": 2,
	"catalog_version": "2026-08-10.evidence-baseline.2",
	"selectors": {},
	"sources": {
		"rideforcesdb.falcon.4804": {
			"initial_state": "corroborative", "state": "corroborative",
			"permitted_contributions": ["reviewed force windows with row and device caveats"],
			"permitted_axes": ["normal_g", "lateral_g", "longitudinal_g"],
			"promotion_prerequisites": ["Cannot promote alone because the recording is flagged unreliable.", "Requires a genuine validated raw artifact or content digest, exact window, verified raw axis schema, row/device mapping, processing chain, complete alignment, confidence rationale, and independent compatible corroboration."],
			"acquisition": "raw_fetch_unavailable", "url": "https://rideforcesdb.com/getRec?id=4804", "recording_id": "4804",
			"retrieved_on": "2026-08-10", "retrieval_context": "RideForcesDB getRec retrieval diagnostic and rideInfo metadata",
			"diagnostic_path": "docs/evidence/fidelity/rideforcesdb/4804-diagnostic.json", "diagnostic_sha256": "13684a1489457596253369e3850486774b1acd812f7f24f84c1f9ba8ffb0aa99",
			"fallback_citations": FALLBACK_CITATIONS["4804"],
			"metadata_artifact_path": "docs/evidence/fidelity/rideforcesdb/4804-ride-info.json", "metadata_artifact_sha256": "f3623b59a9532704f150038161bed03b2950d21d276bb9e5bf2eef9373845564",
			"review_path": "docs/evidence/fidelity/rideforcesdb/4804-review.json", "review_sha256": "347ea5b12bad7e181f7c1a021e5c6d9bea11013d42596cce6d4cf2b98e000e49",
			"row_seat": "Row 7, L seat, ? train", "device": "Apple Watch worn on the wrist", "sample_rate_hz": null, "axis_mapping": {},
			"reliability": "RideForcesDB flags the sole wrist recording unreliable.",
			"processing": ["No raw payload processing; reviewed corpus windows only."],
			"caveats": ["Native sample rate is unknown.", "Reviewed table axes are not a verified raw or rider-frame mapping.", "The wrist shock interval is excluded by the review."],
			"windows": [{"id": "falcon.first_drop", "window_s": [16.3, 17.38]}, {"id": "falcon.launch_2", "window_s": [44.5, 48.5]}, {"id": "falcon.clifftop_slow", "window_s": [78.0, 90.3]}, {"id": "falcon.cliff_dive", "window_s": [90.5, 92.7]}, {"id": "falcon.camelback_pullup", "window_s": [99.02, 102.32]}, {"id": "falcon.camelback_crest", "window_s": [102.9, 109.66]}, {"id": "falcon.final_brakes", "window_s": [151.6, 156.0]}],
		},
		"rideforcesdb.tormenta.6369": {
			"initial_state": "corroborative", "state": "corroborative",
			"permitted_contributions": ["cross-recording support only with pocket and sliding-device caveats"],
			"permitted_axes": ["normal_g", "lateral_g", "longitudinal_g"],
			"promotion_prerequisites": ["Cannot stand in for recording 6383 or measured rider-frame truth.", "A derived observation requires genuine validated content provenance, exact source-local windows, stable axis mapping, and corroboration across 6369, 6383, and the Tormenta POV."],
			"acquisition": "raw_fetch_unavailable", "url": "https://rideforcesdb.com/getRec?id=6369", "recording_id": "6369",
			"retrieved_on": "2026-08-10", "retrieval_context": "RideForcesDB getRec retrieval diagnostic and shared rideInfo metadata",
			"diagnostic_path": "docs/evidence/fidelity/rideforcesdb/6369-diagnostic.json", "diagnostic_sha256": "3e8fe4836c051faa6ad1e50c49c9debea3b8eee6140c9a46292b68f5f80261e3",
			"fallback_citations": FALLBACK_CITATIONS["6369"],
			"metadata_artifact_path": "docs/evidence/fidelity/rideforcesdb/6383-ride-info.json", "metadata_artifact_sha256": "95ce0416f6cc0790c5fd5b07ba7472d240f8b17cbc06d6da6f8821b43eabda61",
			"review_path": "docs/evidence/fidelity/rideforcesdb/6369-review.json", "review_sha256": "9ac0e2fc30d40954a2a74e6920a4b52d01a88f3e8a223b4d3472bca6e7611f6c",
			"row_seat": "Back right seat", "device": "Phone carried in a pocket; exact pocket, body orientation, and model unverified; author warns it might slide", "sample_rate_hz": null, "axis_mapping": {},
			"reliability": "Cross-recording support only; a pocket device may slide or rotate.",
			"processing": ["No raw payload processing; reviewed corpus windows only."],
			"caveats": ["Native sample rate is unknown.", "No stable pocket-device rider-frame mapping exists.", "Recording 6383 times cannot be transferred."],
			"windows": [{"id": "tormenta.drop", "window_s": [7.38, 9.24]}, {"id": "tormenta.drop_pullout", "window_s": [10.2, 13.8]}, {"id": "tormenta.immelmann_1", "window_s": [18.04, 21.58]}, {"id": "tormenta.loop", "window_s": [23.5, 28.52]}, {"id": "tormenta.block_brake", "window_s": [32.0, 44.0]}, {"id": "tormenta.post_block_drop", "window_s": [45.92, 47.34]}, {"id": "tormenta.post_block_pullout", "window_s": [47.7, 50.26]}, {"id": "tormenta.immelmann_2", "window_s": [52.7, 54.58]}, {"id": "tormenta.cutback", "window_s": [56.34, 58.02]}, {"id": "tormenta.brake_bite", "window_s": [61.46, 62.24]}],
		},
		"rideforcesdb.tormenta.6383": {
			"initial_state": "corroborative", "state": "corroborative",
			"permitted_contributions": ["reviewed force windows with row and device caveats"],
			"permitted_axes": ["normal_g", "lateral_g", "longitudinal_g"],
			"promotion_prerequisites": ["Row 2 must remain explicit and recording 6369 times must not be transferred.", "A derived observation requires genuine validated content provenance, exact source-local windows, verified raw axes, complete alignment, and corroboration across 6383, 6369, and the Tormenta POV."],
			"acquisition": "raw_fetch_unavailable", "url": "https://rideforcesdb.com/getRec?id=6383", "recording_id": "6383",
			"retrieved_on": "2026-08-10", "retrieval_context": "RideForcesDB getRec retrieval diagnostic and rideInfo metadata",
			"diagnostic_path": "docs/evidence/fidelity/rideforcesdb/6383-diagnostic.json", "diagnostic_sha256": "a40a3bf86a5f12eeebcb72da2f8b7dde857d17c34b32d98ec862576176610b79",
			"fallback_citations": FALLBACK_CITATIONS["6383"],
			"metadata_artifact_path": "docs/evidence/fidelity/rideforcesdb/6383-ride-info.json", "metadata_artifact_sha256": "95ce0416f6cc0790c5fd5b07ba7472d240f8b17cbc06d6da6f8821b43eabda61",
			"review_path": "docs/evidence/fidelity/rideforcesdb/6383-review.json", "review_sha256": "40ab3696c7aaea6332fc01728987d72a67a421ba4df805c5f38bec33ddc97db6",
			"row_seat": "Row 2, Seat 8, Train 1", "device": "iPhone; exact model unverified", "sample_rate_hz": null, "axis_mapping": {},
			"reliability": "Reviewed row 2 identity, but raw payload, axis mapping, and angle channel remain unavailable.",
			"processing": ["No raw payload processing; reviewed corpus windows only."],
			"caveats": ["Native sample rate is unknown.", "Reviewed table axes are not a verified raw or rider-frame mapping.", "No angle channel is available."],
			"windows": [{"id": "tormenta.drop", "window_s": [7.28, 9.06]}, {"id": "tormenta.drop_pullout", "window_s": [9.84, 13.56]}, {"id": "tormenta.immelmann_1", "window_s": [17.6, 21.16]}, {"id": "tormenta.loop", "window_s": [22.94, 27.58]}, {"id": "tormenta.block_brake", "window_s": [31.8, 42.0]}, {"id": "tormenta.post_block_drop", "window_s": [44.68, 45.62]}, {"id": "tormenta.post_block_pullout", "window_s": [46.08, 48.9]}, {"id": "tormenta.immelmann_2", "window_s": [50.94, 53.16]}, {"id": "tormenta.cutback", "window_s": [54.5, 56.24]}, {"id": "tormenta.brake_bite", "window_s": [59.58, 60.4]}],
		},
		"youtube.coastertalk.continuous.0Ua": {
			"initial_state": "corroborative", "state": "corroborative",
			"permitted_contributions": ["displayed-channel landmarks"], "permitted_axes": [],
			"promotion_prerequisites": ["Review exact source-local landmark windows and identify row, device, sample rate, and displayed-axis mapping.", "Commit qualifying content provenance and a complete alignment; never infer a dense trace or borrow the edited seNR timeline."],
			"url": "https://www.youtube.com/watch?v=0UaOSBGSx20", "video_id": "0UaOSBGSx20", "retrieved_on": "2026-08-10", "retrieval_context": "captured YouTube oEmbed response and sparse live-player review",
			"metadata_artifact_path": "docs/evidence/fidelity/youtube/0UaOSBGSx20-oembed.json", "metadata_artifact_sha256": "eb71dc52f36bda28ee6a9086fcbd6e5397e259f1c9d18624b18076274bf8a83a",
			"review_path": "docs/evidence/fidelity/youtube/0UaOSBGSx20-review.json", "review_sha256": "4e0af882b0280a9d7c7638b2f33a68af7909a6d1d085e61adac987d7869632ba",
			"row_seat": "unknown", "device": "unknown", "sample_rate_hz": null, "axis_mapping": {}, "reliability": "Built-ride leading-view overlay with sparse displayed-channel landmarks only; uploader labels remain unmapped.",
			"processing": ["Sparse manual live-player sampling of uploader-rendered labels only; no video, frame, or raw trace artifact is committed."],
			"caveats": ["Uploader warnings cover consumer-grade sensors, presentation editing, limited sampling, interpolation, and video-frame-rate data loss.", "Raw sample rate, calibration, orientation, filtering, sensor location, row, device, and edit decision list are unknown.", "The three negative Long. labels are sparse approximate unmapped rendered spot checks, not a dense trace or comparison band.", "No generated alignment is established."],
			"windows": [{"id": "0ua.station_dispatch", "time_s": 0.06}, {"id": "0ua.park_straight", "time_s": 25.25}, {"id": "0ua.park_hill_turn", "time_s": 49.171226}, {"id": "0ua.cliff_approach", "time_s": 74.18}, {"id": "0ua.high_terrain_turn", "time_s": 100.45}, {"id": "0ua.cliff_descent", "time_s": 124.37}, {"id": "0ua.fast_park_return", "time_s": 149.39}, {"id": "0ua.compact_park_descent", "time_s": 174.40}, {"id": "0ua.station_return", "time_s": 204.44}],
		},
		"youtube.coastertalk.edited.seNR": {
			"initial_state": "review_pending", "state": "review_pending",
			"permitted_contributions": ["edited visual landmarks only"], "permitted_axes": [],
			"promotion_prerequisites": ["Review exact clip-local visual landmarks and run identity.", "Use landmark-to-landmark alignment only; edits, b-roll, and two runs forbid an absolute ride timeline or dense trace."],
			"url": "https://www.youtube.com/watch?v=seNRpi4wP-s", "video_id": "seNRpi4wP-s", "retrieved_on": "2026-08-10", "retrieval_context": "repository-label metadata diagnostic and edited-review record",
			"metadata_artifact_path": "docs/evidence/fidelity/youtube/seNRpi4wP-s-oembed.json", "metadata_artifact_sha256": "e2a314015ae1a41781ee02b31f58b1358c14b3c6292517ef8b0af508570ea65f",
			"review_path": "docs/evidence/fidelity/youtube/seNRpi4wP-s-review.json", "review_sha256": "a2ee5c8add5e61ae63aa5aab053c6336d01705c83ab8b6f28883f410a789085f",
			"row_seat": "unknown", "device": "unknown", "sample_rate_hz": null, "axis_mapping": {}, "reliability": "Edited visual review only.",
			"processing": ["Repository review only; no local video or dense trace is committed."],
			"caveats": ["Native sample rate is unknown.", "Edits, b-roll, and two runs forbid an absolute timeline.", "No row, device, axis, or generated alignment is established."],
			"windows": [{"id": "falcon.edited_overlay_clip_extent", "window_s": [100.0, 360.0]}],
		},
		"youtube.falcon.backward.J54WKu2nU6o": {
			"initial_state": "observation_only", "state": "observation_only",
			"permitted_contributions": ["order", "geometry", "speed perception", "feel prompts"], "permitted_axes": [],
			"promotion_prerequisites": ["Review exact source-local landmarks with uncertainty and row/camera context.", "Commit qualifying content provenance and complete landmark-to-generated alignment; never infer force axes or transfer another video's clock."],
			"url": "https://www.youtube.com/watch?v=J54WKu2nU6o", "video_id": "J54WKu2nU6o", "retrieved_on": "2026-08-10", "retrieval_context": "captured YouTube oEmbed response and sparse live-player review",
			"metadata_artifact_path": "docs/evidence/fidelity/youtube/J54WKu2nU6o-oembed.json", "metadata_artifact_sha256": "595aa5253b41a2557e3a33bcbd2695a74d9723bb1e49e84fc9f75c4910a26aaf",
			"review_path": "docs/evidence/fidelity/youtube/J54WKu2nU6o-review.json", "review_sha256": "d78534c443817d95b33163136ac1451ae4747dcdebb8266e4cf7fd7f4b2cb9e0",
			"row_seat": "unknown", "device": "unknown", "sample_rate_hz": null, "axis_mapping": {}, "reliability": "Built-ride centered rear-facing view with sparse night landmarks; observation prompts only and exact row undisclosed.",
			"processing": ["Sparse manual live-player review only; no video or frame artifact is committed."],
			"caveats": ["Native sample rate, camera calibration, axis mapping, and generated alignment are unknown.", "Lower-right watermark, night exposure, motion blur, and rapid camera roll limit element-shape certainty."],
			"windows": [{"id": "j54.station_dispatch", "time_s": 0.07}, {"id": "j54.park_straight", "time_s": 29.99}, {"id": "j54.park_bank", "time_s": 59.07}, {"id": "j54.rocky_descent", "time_s": 89.18}, {"id": "j54.elevated_crest", "time_s": 120.71}, {"id": "j54.steep_segment", "time_s": 139.36}, {"id": "j54.park_return", "time_s": 159.43}, {"id": "j54.support_passage", "time_s": 179.50}, {"id": "j54.station_return", "time_s": 219.65}],
		},
		"youtube.falcon.cgi.NFV": {
			"initial_state": "corroborative", "state": "review_pending",
			"permitted_contributions": ["model-to-model geometry", "model-to-model order"], "permitted_axes": [],
			"promotion_prerequisites": ["Remain model-only even if content provenance and landmarks are later committed.", "Where CGI disagrees with real POV, the real POV controls; no measured-truth or force target may be derived."],
			"url": "https://www.youtube.com/watch?v=NFVNGgwZk3c", "video_id": "NFVNGgwZk3c", "retrieved_on": "2026-08-10", "retrieval_context": "YouTube oEmbed retrieval-unavailable diagnostic with repository review labels",
			"metadata_diagnostic_path": "docs/evidence/fidelity/youtube/NFVNGgwZk3c-oembed.json", "metadata_diagnostic_sha256": "3f47dc70b35bf2db5c9a718033c5df61083fbf5c9176f89e4bd123d50e8c139c",
			"review_path": "docs/evidence/fidelity/youtube/NFVNGgwZk3c-review.json", "review_sha256": "5a531ff6fd6187f36e8fda1e9678d6a05a4197af1a4fd3c24c831213f0f19e95",
			"row_seat": "not applicable", "device": "not applicable", "sample_rate_hz": null, "axis_mapping": {}, "reliability": "CGI model-to-model evidence only.",
			"processing": ["Repository CGI review only; no local video analysis is committed."],
			"caveats": ["Native sample rate is unknown.", "CGI is not survey data or measured truth.", "No generated alignment is established."],
			"windows": [{"id": "cgi.camelback.side_profile", "time_s": 11.0}, {"id": "cgi.camelback.end_on", "time_s": 111.0, "uncertainty_s": 1.0}],
		},
		"youtube.falcon.forward.cUURkqyn4Zs": {
			"initial_state": "observation_only", "state": "observation_only",
			"permitted_contributions": ["order", "geometry", "timing landmarks", "feel prompts"], "permitted_axes": [],
			"promotion_prerequisites": ["Review exact source-local landmarks with uncertainty and row/camera context.", "Commit qualifying content provenance and complete landmark-to-generated alignment; never infer force axes or a dense trace."],
			"url": "https://www.youtube.com/watch?v=cUURkqyn4Zs", "video_id": "cUURkqyn4Zs", "retrieved_on": "2026-08-10", "retrieval_context": "repository-label metadata record with reviewed source-local windows",
			"metadata_artifact_path": "docs/evidence/fidelity/youtube/cUURkqyn4Zs-oembed.json", "metadata_artifact_sha256": "4dc75607a7e14de12d8decfc9606832ef2ebda464ff238989f9eea8f6b9a04b6",
			"review_path": "docs/evidence/fidelity/youtube/cUURkqyn4Zs-review.json", "review_sha256": "10da7875407a425a5e17c3f85c64ea008ca53436048a1aa0249b68734306c198",
			"row_seat": "unknown", "device": "unknown", "sample_rate_hz": null, "axis_mapping": {}, "reliability": "Repository-reviewed visual landmarks only.",
			"processing": ["Repository review windows only; no local video or frame analysis is committed."],
			"caveats": ["Native sample rate is unknown.", "Source-local windows have no generated-selector alignment.", "No row, device, camera, or axis mapping is established."],
			"windows": [{"id": "falcon.lsm_lift", "window_s": [21.0, 50.0]}, {"id": "falcon.first_drop", "window_s": [50.5, 55.0]}, {"id": "falcon.cliff_climb", "window_s": [82.0, 114.0]}, {"id": "falcon.crest_hold", "window_s": [114.5, 117.2]}, {"id": "falcon.cliff_dive", "window_s": [128.5, 131.0]}, {"id": "falcon.camelback", "window_s": [132.0, 147.0]}, {"id": "falcon.return_run", "window_s": [150.0, 186.0]}],
		},
		"youtube.falcon.poco8rOnW18": {
			"initial_state": "corroborative", "state": "corroborative",
			"permitted_contributions": ["model-to-model geometry", "model-to-model order"], "permitted_axes": [],
			"promotion_prerequisites": ["Remain NoLimits2 model-only even if content provenance and landmarks are later committed.", "Never use this simulation as measured truth or transfer its clock to real footage."],
			"url": "https://www.youtube.com/watch?v=poco8rOnW18", "video_id": "poco8rOnW18", "retrieved_on": "2026-08-10", "retrieval_context": "captured YouTube oEmbed response and sparse live-player review",
			"metadata_artifact_path": "docs/evidence/fidelity/youtube/poco8rOnW18-oembed.json", "metadata_artifact_sha256": "5776d2ee4dd2840c518774b77c6f6c5517c127f8884493e1f762678ced7ff1ef",
			"review_path": "docs/evidence/fidelity/youtube/poco8rOnW18-review.json", "review_sha256": "99f44129f2731e65170fc524b3dc32dc7e7e022034596ae96642cea0af1c9fd0",
			"row_seat": "not applicable", "device": "not applicable", "sample_rate_hz": null, "axis_mapping": {}, "reliability": "NoLimits2 precreation with mixed third-person and virtual POV; model-to-model evidence only.",
			"processing": ["Sparse manual live-player review only; no video or frame artifact is committed."],
			"caveats": ["Synthetic low-detail terrain and scenery and expressly variable shaping limit as-built correspondence.", "Clifftop shaping and order remain unconfirmed; real built-ride POV controls wherever sources disagree.", "This simulation cannot establish measured truth, transfer its clock, or supply generated alignment."],
			"windows": [{"id": "poco.opening", "time_s": 0.10}, {"id": "poco.park_element", "time_s": 43.63}, {"id": "poco.desert_curve", "time_s": 88.56}, {"id": "poco.elevated_arch", "time_s": 133.76}, {"id": "poco.supported_grade", "time_s": 148.74}, {"id": "poco.low_return", "time_s": 163.71}, {"id": "poco.virtual_pov_start", "time_s": 170.69}, {"id": "poco.steep_ascent", "time_s": 178.69}, {"id": "poco.rocky_ascent", "time_s": 223.89}, {"id": "poco.modeled_hill", "time_s": 268.82}, {"id": "poco.park_return", "time_s": 314.02}],
		},
		"youtube.falcon.sdXGD9kMR7s": {
			"initial_state": "observation_only", "state": "observation_only",
			"permitted_contributions": ["order", "geometry", "timing landmarks", "feel prompts"], "permitted_axes": [],
			"promotion_prerequisites": ["Review exact source-local landmarks with uncertainty and front-row/camera context.", "Commit qualifying content provenance and complete landmark-to-generated alignment; never infer force axes or transfer another video's clock."],
			"url": "https://www.youtube.com/watch?v=sdXGD9kMR7s", "video_id": "sdXGD9kMR7s", "retrieved_on": "2026-08-10", "retrieval_context": "captured YouTube oEmbed response and sparse live-player review",
			"metadata_artifact_path": "docs/evidence/fidelity/youtube/sdXGD9kMR7s-oembed.json", "metadata_artifact_sha256": "badb63ae7143267d526a4d6d32dbdc85f280506cf2a8663280df760f87b12361",
			"review_path": "docs/evidence/fidelity/youtube/sdXGD9kMR7s-review.json", "review_sha256": "9dd4b8ed8f5d4bfd8b67f2218c65ed681fcb912fe55a5599e34770919d6192df",
			"row_seat": "front-row view per title; exact camera mount undisclosed", "device": "unknown", "sample_rate_hz": null, "axis_mapping": {}, "reliability": "Built-ride front-row view per title with sparse visual landmarks; observation prompts only.",
			"processing": ["Sparse manual live-player review only; no video or frame artifact is committed."],
			"caveats": ["Native sample rate, camera calibration, axis mapping, and generated alignment are unknown.", "Leading car nose, curved bar, lower-right watermark, sun glare, and lens or dust spots obstruct the view.", "The editorial length card is not telemetry."],
			"windows": [{"id": "sdx.station_dispatch", "time_s": 0.07}, {"id": "sdx.park_straight", "time_s": 28.93}, {"id": "sdx.park_bank", "time_s": 58.81}, {"id": "sdx.rock_face_pitch", "time_s": 88.87}, {"id": "sdx.cliff_edge", "time_s": 118.94}, {"id": "sdx.elevated_crest", "time_s": 138.86}, {"id": "sdx.low_terrain_turn", "time_s": 158.97}, {"id": "sdx.park_run", "time_s": 178.88}, {"id": "sdx.station_return", "time_s": 218.91}],
		},
		"youtube.i305.overlay.wX7": {
			"initial_state": "corroborative", "state": "review_pending",
			"permitted_contributions": ["vertical/normal-g windows only"], "permitted_axes": ["normal_g"],
			"promotion_prerequisites": ["Commit qualifying content provenance and exact reviewed vertical windows with the documented uncertainty and uploader synchronization caveat.", "No lateral or longitudinal axis may be inferred; complete alignment and independent compatible corroboration are required."],
			"url": "https://www.youtube.com/watch?v=wX7uHKj-Ujc", "video_id": "wX7uHKj-Ujc", "retrieved_on": "2026-08-10", "retrieval_context": "YouTube oEmbed retrieval-unavailable diagnostic with repository overlay review",
			"metadata_diagnostic_path": "docs/evidence/fidelity/youtube/wX7uHKj-Ujc-oembed.json", "metadata_diagnostic_sha256": "bc41ffd9692da259172046a6a204a2f544d967a789e1d2cf62d228d9e1507fba",
			"review_path": "docs/evidence/fidelity/youtube/wX7uHKj-Ujc-review.json", "review_sha256": "9fd3a7ec8e8094abfc9148b2d74600d5a1ec238466a66b7dd02b81a8a43277a2",
			"row_seat": "unknown", "device": "unknown", "sample_rate_hz": null, "axis_mapping": {}, "reliability": "Repository-reviewed normal-g overlay windows only.",
			"processing": ["Repository overlay review only; no local video or raw trace is committed."],
			"caveats": ["Native sample rate is unknown.", "Only normal-g is reviewed; lateral and longitudinal mappings are unavailable.", "Uploader synchronization and no generated alignment remain caveats."],
			"windows": [{"id": "i305.first_banked_turn", "window_s": [8.7, 12.7], "axis": "normal_g", "uncertainty_s": 0.15}, {"id": "i305.ejector_hill_1", "window_s": [15.4, 18.2], "axis": "normal_g", "uncertainty_s": 0.15}],
		},
		"youtube.tormenta.forward.AHjk": {
			"initial_state": "observation_only", "state": "review_pending",
			"permitted_contributions": ["order", "geometry", "timing landmarks", "feel prompts"], "permitted_axes": [],
			"promotion_prerequisites": ["Capture genuine provider/content provenance without treating repository labels as exact provider metadata.", "Review exact source-local landmarks and complete alignment; force claims require compatible corroboration from both Tormenta recordings."],
			"url": "https://www.youtube.com/watch?v=AHjk2R4da_I", "video_id": "AHjk2R4da_I", "retrieved_on": "2026-08-10", "retrieval_context": "YouTube oEmbed retrieval-unavailable diagnostic with repository review labels",
			"metadata_diagnostic_path": "docs/evidence/fidelity/youtube/AHjk2R4da_I-oembed.json", "metadata_diagnostic_sha256": "f048bca08164a572c96a5a0eaeb1b7523e5193881bc53725e4a9bd93b60924ba",
			"review_path": "docs/evidence/fidelity/youtube/AHjk2R4da_I-review.json", "review_sha256": "d42e433dfe335beb3b76d40c640cdf0e690ffcafe141c1ed01e50f8c22102715",
			"row_seat": "unknown", "device": "unknown", "sample_rate_hz": null, "axis_mapping": {}, "reliability": "Repository sequence review only; provider metadata is not independently fetched.",
			"processing": ["Repository review only; no local video or frame analysis is committed."],
			"caveats": ["Native sample rate is unknown.", "No exact provider title or channel is established.", "No source-second landmark, row, device, axis, or generated alignment is established."], "windows": [],
		},
	},
	"transforms": {
		"fictional.gz-positive@1": {"kind": "scale", "axis": "normal_g", "polarity": "positive", "factor": 1.3333333333, "formula": "target_force_g = observed_force_g * 1.3333333333", "approval": "explicit user decision 2026-08-09"},
		"fictional.gz-negative@1": {"kind": "scale", "axis": "normal_g", "polarity": "negative", "factor": 1.5, "formula": "target_force_g = observed_force_g * 1.5", "approval": "explicit user decision 2026-08-09"},
		"fictional.gy-positive@1": {"kind": "scale", "axis": "lateral_g", "polarity": "positive", "factor": 1.5666666667, "formula": "target_force_g = observed_force_g * 1.5666666667", "approval": "explicit user decision 2026-08-09"},
		"fictional.gy-negative@1": {"kind": "scale", "axis": "lateral_g", "polarity": "negative", "factor": 1.5666666667, "formula": "target_force_g = observed_force_g * 1.5666666667", "approval": "explicit user decision 2026-08-09"},
		"fictional.gx-negative@1": {"kind": "scale", "axis": "longitudinal_g", "polarity": "negative", "factor": 1.7142857143, "formula": "target_force_g = observed_force_g * 1.7142857143", "approval": "explicit user decision 2026-08-09"},
		"observed.identity@1": {"kind": "identity", "factor": 1.0, "formula": "target_value = observed_value", "approval": "identity; no transform"},
	},
	"observations": [],
	"targets": [],
	"review_prompts": [
		{"id": "review.ride_feel", "category": "ride feel", "prompt": "Compare generated act ordering and connective flow against source-local POV landmarks only; do not transfer timestamps or proportionally scale independent video clocks.", "source_ids": ["youtube.falcon.backward.J54WKu2nU6o", "youtube.falcon.forward.cUURkqyn4Zs", "youtube.falcon.sdXGD9kMR7s"], "issues": [1, 10, 11, 13, 15, 16]},
		{"id": "review.speed_perception", "category": "speed perception", "prompt": "Compare generated speed perception against source-local terrain, support, and park-reference landmarks only; do not infer speed from a global POV duration ratio.", "source_ids": ["youtube.falcon.backward.J54WKu2nU6o", "youtube.falcon.sdXGD9kMR7s"], "issues": [2, 6, 8, 11, 12]},
		{"id": "review.element_shaping", "category": "element shaping", "prompt": "Do crests, pullouts, inversions, and roll timing read as deliberate family-specific shapes?", "source_ids": ["youtube.falcon.forward.cUURkqyn4Zs", "youtube.falcon.cgi.NFV"], "issues": [4, 5, 14, 16]},
		{"id": "review.support_overlap", "category": "support overlap", "prompt": "Do side and top views expose any track/support overlap around inversions or crossings?", "source_ids": ["youtube.falcon.cgi.NFV"], "issues": [7, 16]},
		{"id": "review.coastertalk_overlay_spot_checks", "category": "ride feel", "prompt": "Review the three source-local uploader-labelled Long. spot checks (-0.30 g, -0.19 g, and approximately -0.58 g) only as unscored, approximate, unmapped rendered labels; they are not a calibrated trace, rider-axis trace, or comparison band.", "source_ids": ["youtube.coastertalk.continuous.0Ua"], "issues": [3, 10, 13, 15, 16]},
		{"id": "review.terrain_clearance", "category": "terrain/clearance", "prompt": "Compare the generated cliff, high-terrain, and low-return views landmark-to-landmark against the real built-ride POVs; do not infer an AGL band or proportionally scale independent video clocks.", "source_ids": ["youtube.coastertalk.continuous.0Ua", "youtube.falcon.backward.J54WKu2nU6o", "youtube.falcon.sdXGD9kMR7s"], "issues": [6, 8, 12]},
	],
	"evidence_gaps": [
		{"id": "gap.force_bands", "description": "Sparse rendered video points lack raw sampling, device/row calibration, rider-axis mapping, full source-to-generated alignment, and corroboration; no multiplier or duration ratio closes those gaps.", "source_ids": ["rideforcesdb.falcon.4804", "rideforcesdb.tormenta.6369", "rideforcesdb.tormenta.6383", "youtube.i305.overlay.wX7", "youtube.coastertalk.continuous.0Ua"], "issues": [3, 9, 13]},
		{"id": "gap.absolute_agl", "description": "The corpus supports terrain-hugging visual review but no surveyed per-element AGL comparison band.", "source_ids": ["youtube.falcon.forward.cUURkqyn4Zs", "youtube.falcon.cgi.NFV"], "issues": [6, 12]},
		{"id": "gap.connective_micro_elements", "description": "No source supplies a reusable numeric target for connective micro-elements or transitions.", "source_ids": ["youtube.falcon.forward.cUURkqyn4Zs", "youtube.falcon.sdXGD9kMR7s"], "issues": [1, 4, 10, 15, 16]},
		{"id": "gap.coasting_drag", "description": "Observed visual speed trends do not establish a transferable drag coefficient or speed-loss band.", "source_ids": ["youtube.falcon.backward.J54WKu2nU6o", "youtube.falcon.forward.cUURkqyn4Zs"], "issues": [2, 8, 11]},
		{"id": "gap.support_geometry", "description": "No reusable numeric support-clearance or crossing target is present in the reviewed corpus.", "source_ids": ["youtube.falcon.cgi.NFV"], "issues": [7]},
	],
}
